### ISSUE TITLE
增加服务器或者用新的groupid存在疑问

### ISSUE THREAD

**Issue by yanghui527** [adyliu/jafka#45]
增加服务器新端口或者启用新的groupid，都会收到之前已经发送过的历史消息，如果不想收到以往的消息，是否有参数进行设置？

**Comment by adyliu** [comment]
"增加服务器新端口" 是什么意思？

启用新的groupid会从头收取消息，如果不想从头收取，可手动/程序修改zookeeper中的消费消息的commit。也可以消费一遍即可停止。
另外，历史较大的日志信息，可以考虑自动回滚机制，防止文件过大。

相同的groupid会从上次消费消息的位置开始。

**Comment by yanghui527** [comment]
Hi,早上好

增加新服务器端口是指增加新的server，例如：我已经启动9092，9093端口，使用这个两个端口一段时间，我增加了9094，
这个时候consumer又会收到之前已经接收过的消息

**Comment by yanghui527** [comment]
大神，你好！
	再请教一下，我使用kafka不会出现这样的问题，但是出现了另外一个问题，启动多个Consumer时，并没有进行负载均衡，一直只有一个Consumer收到消息，另外的Consumer一直都没有收到过，这块jafka可以做得很好

**Comment by adyliu** [comment]
brokers一共有多少片消息，客户端consumer的数量和其匹配即可。

比如一共有6个partition，三个consumer，每个consumer有2个线程，这样每个consumer就可以消费两个patition。

加入第一个consumer就有5个线程，那么第一个consumer消费5个partition,第二个consumer消费1个partition,最后一个consumer无消息可消费。
