### ISSUE TITLE
 一次 Fetch 只能获取一个 LogSegment 的内容吗？

### ISSUE THREAD

**Issue by wanggaohang** [adyliu/jafka#49]
在 Log.read(long offset, int length) 方法中看到一次 Fetch 操作只会二分寻找 offset 所在的那个 LogSegment 并最多只读到该日志段的末尾，如果 offset + length 横跨多个 LogSegment 的情况下该怎么处理？

**Comment by adyliu** [comment]
length 只是建议，或者说不超过。一次只能读取一个LogSegment，下次读取的时候自动读取第二个LogSegment。
